### ISSUE TITLE
[Issue] Can't automatically load todo.txt file on starting script

### ISSUE THREAD

**Issue by AaronKnowls** [KrisNumber24/KanbanTxt#1]
Hi! Thank you for this useful script.

- I have an issue with using the --file=
   - The script opens fine, but it doesn't load the todo.txt file.
   - By trying the opening command in windows command line, I found out it wasn't recognizing spaces in paths.
      - So I change the space the path contain to %20%.
         - Then there were no more errors in windows command but still the script opens without the todo.txt and I have to load manually.

I might be missing something very obvious but I can't figure it out.

Thank you so much for your time and for sharing this script.

**Comment by KrisNumber24** [comment]
Hi!
I'm glad you find my script useful. 😄 
Thank you for your feedback. I'll work on it as soon as I have a moment! 
I'll let you know when I've made any progress on this issue.

**Comment by AaronKnowls** [comment]
That's great news! 
Thank you so so much :)

**Comment by KrisNumber24** [comment]
Hello!
I've run some tests and I think it's best to enclose the path containing white spaces between double quotes in the command line. If I'm right, the % notations (percent-encoding) is more used for URIs (like web URLs for example) and not for file paths. Thus your command should look like this:
```bash
python KanbanTxt.py --file "C:\Users\MyUser\Documents\my dir with spaces\my file with spaces.txt"
```
Let me know if it works, and if not, I'll do some more tests.

**Comment by AaronKnowls** [comment]
It does work!!!! You're a genius, a generous genius :)

Thank you, KrisNumber24!!

**Comment by AaronKnowls** [comment]
I guess I should close this now. Bravo!

**Comment by KrisNumber24** [comment]
Hello !
Sorry I've been a bit busy lately. I'm glad to see the problem is solved. 
Thanks for your support. 😃
